#!/bin/sh
#
# Clone various repositories and move them to the proper place.

# Initialize all the submodules.
git submodule update --init --recursive

# install(from, to, script)

install() {
    mkdir -p "$(dirname "$2")"

    [ -L "$2" ] && rm "$2"

    if [ -f "$2" ] || [ -d "$2" ]; then
        echo "$1 is already installed"
    else
        echo "$1 -> $2"
        if [ -d "$PWD/$1" ]; then
            ln -s "$PWD/$1" "$2"
        else
            link "$PWD/$1" "$2"
        fi
	script="$PWD/scripts/$1"
	if [ -f "$script" ]; then
		(
			cd "$2" || exit
			sh "$script"
		)
	fi
    fi
}

# Install the profile first, as it has all the PATH modifications.
install profile  ~/.profile

# shellcheck disable=1090
. ~/.profile

# Install various files
make install -C sub/sowm

make install -C sub/utils
( cd sub/utils/sfeed_fmt || exit; go install )

# Install vim-plug for Neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

install sub/nvim  ~/.config/nvim
install sub/sowm  ~/src/ui/sowm
install sub/st    ~/src/ui/st
install sub/utils ~/src/utils
