#!/bin/sh
#
# Clone various repositories and move them to the proper place.

# Initialize all the submodules.
git submodule update --init --recursive

install() {
    mkdir -p "$(dirname "$2")"
    [ -d "$1" ] || ln -s "$1" "$2"
}

# Install various files
make install -C sowm

install nvim ~/.config/nvim
install sowm ~/src/repos/ui/sowm
