#!/bin/sh
#
# Clone various repositories and move them to the proper place.

# install(from, to, script)

case "$1" in
    -f) FORCE=1 ;;
esac

tilde() {
    echo "$*" | sed "s|$HOME|~|"
}

install() {
    src="$1"
    dest="$2"
    destdir="$(dirname "$2")"
    name="$(basename "$src")"
    srcdir="$PWD/src/$name" # Must be absolute path for symlinks to work right.

    mkdir -p "$destdir"
    mkdir -p src

    [ "$FORCE" ] && { [ -L "$dest" ] || [ -d "$dest" ]; } && rm -rf "$dest"

    if [ -L "$dest" ] || [ -d "$dest" ]; then
        echo "$(tilde "$dest") is already installed"
    else
        mkdir -p "$destdir"
        [ "$FORCE" ] && [ -d "$srcdir" ] && rm -rf "$srcdir"
        [ -d "$srcdir" ] || git clone "$src" "$srcdir"
        cp -r "$srcdir" "$dest"
        script="$PWD/scripts/$name"
        if [ -f "$script" ]; then
            (
                cd "$dest" || exit
                sh "$script"
            )
        fi
    fi
}

# Install the profile first, as it has all the PATH modifications.
cp profile ~/.profile

# shellcheck disable=1090
. ~/.profile

# Initialize these directories for reasons.

mkdir -p ~/src/repos
mkdir ~/bin

install https://github.com/dragonsourced/scripts ~/src/scripts
install https://github.com/dragonsourced/nvim    ~/.config/nvim
install https://github.com/dragonsourced/sowm    ~/src/ui/sowm
install https://github.com/dragonsourced/st      ~/src/ui/st
install https://github.com/dragonsourced/utils   ~/src/utils
install https://github.com/dragonsourced/misc    ~/src/misc
