#!/bin/sh
#
# Upgrade submodules to the latest version.

upgrade() {
    cd "$*" || return
    git fetch
    git checkout master
    git merge origin/master
    git add .
}

pwd="$PWD"
for sub in sub/*; do
    upgrade "$pwd/$sub"
done
