#!/bin/sh

# Install vim-plug.

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# A hacky workaround for my lack of knowledge, which runs the PlugInstall
# command before killing the program 10 seconds later.

echo PlugInstall | nvim -e > /dev/null &
pid=$!
sleep 10
kill "$pid"
